[package]
name = "webglee"
version = "0.1.0"
authors = ["leod <subtle.frustration@proton.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
golem = { version = "0.1.7", features = ["web-sys"] }
wasm-bindgen = "0.2"
