[package]
name = "webglee"
version = "0.1.0"
authors = ["Leonard Dahlmann <leo.dahlmann@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
thiserror = "1.0"
wasm-bindgen = "0.2"
nalgebra = "0.22"
fontdue = { git = "https://github.com/mooman219/fontdue.git" }

#golem = { version = "0.1.7", features = ["web-sys"] }
golem = { git = "https://github.com/ryanisaacg/golem.git", features = ["web-sys"] }
#golem = { git = "https://github.com/leod/golem.git", branch = "texture_f32", features = ["web-sys"] }
#golem = { path = "../golem", features = ["web-sys"] }

[dependencies.web-sys]
version = "0.3"
features = [
    "WebGlRenderingContext",
    "HtmlCanvasElement",
    "Window",
    "KeyboardEvent",
    "Event",
    "FocusEvent",
    "CssStyleDeclaration",
]

[workspace]
members = [
    "examples/playground",
]