[package]
name = "webglee"
version = "0.1.0"
authors = ["leod <subtle.frustration@proton.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
thiserror = "1.0"
wasm-bindgen = "0.2"
#golem = { version = "0.1.7", features = ["web-sys"] }
golem = { git = "https://github.com/leod/golem", branch = "fix-log-typo", features = ["web-sys"] }
nalgebra = "0.22"

[dependencies.web-sys]
version = "0.3"
features = [
    "WebGlRenderingContext",
    "HtmlCanvasElement",
    "Window",
    "KeyboardEvent",
    "Event",
    "FocusEvent",
]

[workspace]
members = [
    "examples/playground",
]