[package]
name = "malen"
version = "0.1.0"
authors = ["Leonard Dahlmann <leo.dahlmann@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
thiserror = "1.0"
wasm-bindgen = "0.2"
nalgebra = "0.23"
fontdue = "0.5"

golem = { git = "https://github.com/ryanisaacg/golem.git", features = ["web-sys"] }

[dependencies.web-sys]
version = "0.3"
features = [
    "WebGlRenderingContext",
    "HtmlCanvasElement",
    "Window",
    "KeyboardEvent",
    "Event",
    "FocusEvent",
    "CssStyleDeclaration",
]

[workspace]
members = [
    "examples/playground",
]
