use web_sys::{KeyboardEvent, MouseEvent};

use nalgebra::Point2;

#[derive(Debug, Clone)]
pub enum Event {
    Focused,
    Unfocused,
    KeyPressed(Key),
    KeyReleased(Key),
    MousePressed(Button),
    MouseReleased(Button),
    MouseMoved(Point2<f64>),
}

/// A key that can be pressed.
///
/// This enum has been copied almost exactly from winit.
/// Source: https://github.com/rust-windowing/winit/blob/a2db4c0a320aafc10d240c432fe5ef4e4d84629d/src/event.rs#L774
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Key {
    /// The '1' key over the letters.
    Key1,
    /// The '2' key over the letters.
    Key2,
    /// The '3' key over the letters.
    Key3,
    /// The '4' key over the letters.
    Key4,
    /// The '5' key over the letters.
    Key5,
    /// The '6' key over the letters.
    Key6,
    /// The '7' key over the letters.
    Key7,
    /// The '8' key over the letters.
    Key8,
    /// The '9' key over the letters.
    Key9,
    /// The '0' key over the 'O' and 'P' keys.
    Key0,

    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,

    /// The Escape key, next to F1.
    Escape,

    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    F13,
    F14,
    F15,
    F16,
    F17,
    F18,
    F19,
    F20,
    F21,
    F22,
    F23,
    F24,

    /// Print Screen/SysRq.
    Snapshot,
    /// Scroll Lock.
    Scroll,
    /// Pause/Break key, next to Scroll lock.
    Pause,

    /// `Insert`, next to Backspace.
    Insert,
    Home,
    Delete,
    End,
    PageDown,
    PageUp,

    Left,
    Up,
    Right,
    Down,

    /// The Backspace key, right over Enter.
    Backspace,
    /// The Enter key.
    Return,
    /// The space bar.
    Space,

    /// The "Compose" key on Linux.
    Compose,

    Caret,

    Numlock,
    Numpad0,
    Numpad1,
    Numpad2,
    Numpad3,
    Numpad4,
    Numpad5,
    Numpad6,
    Numpad7,
    Numpad8,
    Numpad9,

    AbntC1,
    AbntC2,
    Add,
    Apostrophe,
    Apps,
    At,
    Ax,
    Backslash,
    Calculator,
    Capital,
    Colon,
    Comma,
    Convert,
    Decimal,
    Divide,
    Equals,
    Grave,
    Kana,
    Kanji,
    LAlt,
    LBracket,
    LControl,
    LShift,
    LWin,
    Mail,
    MediaSelect,
    MediaStop,
    Minus,
    Multiply,
    Mute,
    MyComputer,
    NavigateForward,  // also called "Prior"
    NavigateBackward, // also called "Next"
    NextTrack,
    NoConvert,
    NumpadComma,
    NumpadEnter,
    NumpadEquals,
    OEM102,
    Period,
    PlayPause,
    Power,
    PrevTrack,
    RAlt,
    RBracket,
    RControl,
    RShift,
    RWin,
    Semicolon,
    Slash,
    Sleep,
    Stop,
    Subtract,
    Sysrq,
    Tab,
    Underline,
    Unlabeled,
    VolumeDown,
    VolumeUp,
    Wake,
    WebBack,
    WebFavorites,
    WebForward,
    WebHome,
    WebRefresh,
    WebSearch,
    WebStop,
    Yen,
    Copy,
    Paste,
    Cut,
}

/// State of buttons that can be pressed.
///
/// https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Button {
    Primary,
    Auxiliary,
    Secondary,
}

impl Key {
    pub fn from_keyboard_event(event: &KeyboardEvent) -> Option<Self> {
        use Key::*;

        // Source:
        // https://github.com/rust-windowing/winit/blob/e4754999b7e7f27786092a62eda5275672d74130/src/platform_impl/web/web_sys/event.rs#L64
        Some(match &event.code()[..] {
            "Digit1" => Key1,
            "Digit2" => Key2,
            "Digit3" => Key3,
            "Digit4" => Key4,
            "Digit5" => Key5,
            "Digit6" => Key6,
            "Digit7" => Key7,
            "Digit8" => Key8,
            "Digit9" => Key9,
            "Digit0" => Key0,
            "KeyA" => A,
            "KeyB" => B,
            "KeyC" => C,
            "KeyD" => D,
            "KeyE" => E,
            "KeyF" => F,
            "KeyG" => G,
            "KeyH" => H,
            "KeyI" => I,
            "KeyJ" => J,
            "KeyK" => K,
            "KeyL" => L,
            "KeyM" => M,
            "KeyN" => N,
            "KeyO" => O,
            "KeyP" => P,
            "KeyQ" => Q,
            "KeyR" => R,
            "KeyS" => S,
            "KeyT" => T,
            "KeyU" => U,
            "KeyV" => V,
            "KeyW" => W,
            "KeyX" => X,
            "KeyY" => Y,
            "KeyZ" => Z,
            "Escape" => Escape,
            "F1" => F1,
            "F2" => F2,
            "F3" => F3,
            "F4" => F4,
            "F5" => F5,
            "F6" => F6,
            "F7" => F7,
            "F8" => F8,
            "F9" => F9,
            "F10" => F10,
            "F11" => F11,
            "F12" => F12,
            "F13" => F13,
            "F14" => F14,
            "F15" => F15,
            "F16" => F16,
            "F17" => F17,
            "F18" => F18,
            "F19" => F19,
            "F20" => F20,
            "F21" => F21,
            "F22" => F22,
            "F23" => F23,
            "F24" => F24,
            "PrintScreen" => Snapshot,
            "ScrollLock" => Scroll,
            "Pause" => Pause,
            "Insert" => Insert,
            "Home" => Home,
            "Delete" => Delete,
            "End" => End,
            "PageDown" => PageDown,
            "PageUp" => PageUp,
            "ArrowLeft" => Left,
            "ArrowUp" => Up,
            "ArrowRight" => Right,
            "ArrowDown" => Down,
            "Backspace" => Backspace,
            "Enter" => Return,
            "Space" => Space,
            "Compose" => Compose,
            "Caret" => Caret,
            "NumLock" => Numlock,
            "Numpad0" => Numpad0,
            "Numpad1" => Numpad1,
            "Numpad2" => Numpad2,
            "Numpad3" => Numpad3,
            "Numpad4" => Numpad4,
            "Numpad5" => Numpad5,
            "Numpad6" => Numpad6,
            "Numpad7" => Numpad7,
            "Numpad8" => Numpad8,
            "Numpad9" => Numpad9,
            "AbntC1" => AbntC1,
            "AbntC2" => AbntC2,
            "NumpadAdd" => Add,
            "Quote" => Apostrophe,
            "Apps" => Apps,
            "At" => At,
            "Ax" => Ax,
            "Backslash" => Backslash,
            "Calculator" => Calculator,
            "Capital" => Capital,
            "Semicolon" => Semicolon,
            "Comma" => Comma,
            "Convert" => Convert,
            "NumpadDecimal" => Decimal,
            "NumpadDivide" => Divide,
            "Equal" => Equals,
            "Backquote" => Grave,
            "Kana" => Kana,
            "Kanji" => Kanji,
            "AltLeft" => LAlt,
            "BracketLeft" => LBracket,
            "ControlLeft" => LControl,
            "ShiftLeft" => LShift,
            "MetaLeft" => LWin,
            "Mail" => Mail,
            "MediaSelect" => MediaSelect,
            "MediaStop" => MediaStop,
            "Minus" => Minus,
            "NumpadMultiply" => Multiply,
            "Mute" => Mute,
            "LaunchMyComputer" => MyComputer,
            "NavigateForward" => NavigateForward,
            "NavigateBackward" => NavigateBackward,
            "NextTrack" => NextTrack,
            "NoConvert" => NoConvert,
            "NumpadComma" => NumpadComma,
            "NumpadEnter" => NumpadEnter,
            "NumpadEquals" => NumpadEquals,
            "OEM102" => OEM102,
            "Period" => Period,
            "PlayPause" => PlayPause,
            _ => return None,
        })
    }
}

impl Button {
    pub fn from_mouse_event(event: &MouseEvent) -> Option<Self> {
        use Button::*;

        // https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/buttons
        Some(match event.button() {
            0 => Primary,
            1 => Auxiliary,
            2 => Secondary,
            _ => return None,
        })
    }
}
